services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "1234:1234"
    depends_on:
      - server
    command: ["node", "server.js"]

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    command: ["node", "server.js"]